### ISSUE TITLE
More choice

### ISSUE THREAD

**Issue by ghost** [Super-Baleine/ENERGY#1]
If you want energy of a particle, you must use that expression : 
E² = sqrt(m² * c^4 + p² * c²) or E = h V

For a system (in general) : 
E = Ec + Ep

;)

**Comment by Super-Baleine** [comment]
Yea, but that's not the energy of a particle or a relative system.
That's the energy of a liquid in function of its mass.

But, I'll write another program to calculate the energy of a particle/relative system.

**Comment by Super-Baleine** [comment]
c = 3.10⁸, right ?
what does 'p' mean ?

**Comment by ghost** [comment]
If it's only for a liquid, be more specific in the title xD

I think it would be a good idea to let more choice.

I made a mistake, it's : 
E² = m^2 c^4 + p^2 c^2 with : 
- p = γ m v (the impulsion)
- γ (the lorentzian factor)
- v (the particle speed)
- c (the light speed)

c^2 = (299792458)^2 (exactly)
c^4 = (299792458)^4 (exactly)

**Comment by Super-Baleine** [comment]
xDDD

Yea, I'm writing another code for a energy of a particle.

y is gave or you have to define it ?

**Comment by ghost** [comment]
The lorentzian factor is : 
γ = 1/(1 - v^2 / c^2)^1/2

**Comment by Super-Baleine** [comment]
shit, too many operations xD

what is m? The mass ? Noooope, yes ?

**Comment by ghost** [comment]
Yes it's the mass

**Comment by Super-Baleine** [comment]
Okay, thanks, I'll finish this for tonight

**Comment by Super-Baleine** [comment]
Done, tell me is there's a mistake
